### ISSUE TITLE
Cheque reprint bug

### ISSUE THREAD

**Issue by sdragnev** [JMAConsulting/biz.jmaconsulting.grantprograms#245]
There's a bug when reprinting large number of cheques.

If the original print had more than one cheque per person, the reprint gets very confused and does the following:

* Does not print the cheque that's immediately prior the two cheques person
* It puts the grant summary (in the cheque header) of the skipped cheque on the first cheque of the two cheques person
* Puts all grants in the summary in the second cheque for the two cheques person but when it sums them up, it only sums up to the amount for second cheque

I'll take a look and if I manage to fix, I'll make the change on master and pull on new dev branch (and nei).

**Comment by sdragnev** [comment]
Symptom is a red herring, looks like.
Problem is caused by the payment missing from civicrm_entity_payment despite it being present in civicrm_payment.

Bug is not in reprint but original print. It's related to an issue where payments don't get combined when we limit the cheques per PDF (to avoid timing out the pdf generator). A person will end up with 2 payments, but civicrm_entity_payment would not be updated correctly.

Gah.

**Comment by JoeMurray** [comment]
I agree with strategy of fixing to ensure payments get combined properly. We should be able to tweak the code and queries to ensure that payments to same person are not split between batches.

**Comment by sdragnev** [comment]
(Just thinking outl oud here + documentation)

The payment creation code hinges on the assumption that payments have been combined earlier. Unfortunately, the mysql LIMIT throws that assumption off completely.

LIMIT has no way to look "into the future" to know more of the same contact are coming from a later query. It was a quick fix for the pdf time out issue but it doesn't really work.

I think my best bet is to make the split happen later on in the code rather than through mysql.
Otherwise it'll require too many changes to the way payments are grouped which is just asking for new bugs.

**Comment by JoeMurray** [comment]
Could you provide a line reference to these queries, in case I can see a way to fix this through subqueries or something?

**Comment by sdragnev** [comment]
CRM/Grant/Form/Task/GrantPayment.php:166
Then the LIMIT is just tacked on to line 182.

**Comment by sdragnev** [comment]
I think it's just best to do the separation into files at the end when the pdf is being prepared.
I'll fix it sometime tomorrow.

I think it'll also make the code a bit clearer than preprocessing the limit before any payments are created. The two should be separate anyway.

**Comment by JoeMurray** [comment]
Not the most elegant code. I'll leave it to your discretion.
