### ISSUE TITLE
Option values no longer useful for grant variables

### ISSUE THREAD

**Issue by sdragnev** [JMAConsulting/biz.jmaconsulting.grantprograms#246]
It seems like, starting with 4.5, option values are no longer modifiable through the UI.
http://forum.civicrm.org/index.php/topic,35775.0.html

We use those to store various grant settings (max grant payout, modifier, number of cheques per file, etc).
Having to run sql queries to change those is not realistic.

We need to figure out a new way to store variables and then change the installation scripts and code that looks them up.

**Comment by sdragnev** [comment]
To my knowledge, civi lacks a table with custom variables table similar to Drupal's "variable".
That would be the ideal place for this.

A possible solution would be a custom table to store those options but that would be a silly-looking <key|value> pairs table with only a handful of records. Not ideal.

**Comment by JoeMurray** [comment]
Yeah, let's just use the description field or something if it comes to that.

**Comment by sdragnev** [comment]
You think there's a chance we'll get the values editable through the UI again?

**Comment by pradpnayak** [comment]
Hi Stan,

You can add Value field through buildform hook.

You can refer https://github.com/JMAConsulting/biz.jmaconsulting.mte/commit/5a001241d9911611daa533ebf70b1b3132f8c830.

HTH 
Pradeep

**Comment by sdragnev** [comment]
Thanks, Pradeep.
