### ISSUE TITLE
Merging contacts doesn't move civicrm_payment entry

### ISSUE THREAD

**Issue by sdragnev** [JMAConsulting/biz.jmaconsulting.grantprograms#247]
The payment record remains attached to the deleted contact messing up payment reports (since deleted contacts are automatically hidden on the report).

**Comment by sdragnev** [comment]
Fixed in 4.6-dev. Not sure if this issue should be closed or you want to pull into master first.
Not touching the master branch since it's too different from our install and I don't want to test everything twice. (though this particular commit should be a straight-forward merge)

**Comment by JoeMurray** [comment]
Thanks, Stan. Pradeep please merge into master.

**Comment by JoeMurray** [comment]
@Edzelopez please check if properly merged then close when done.
