### ISSUE TITLE
The list of grants below grant edit form includes the grant being edited

### ISSUE THREAD

**Issue by sdragnev** [JMAConsulting/biz.jmaconsulting.grantprograms#252]
Title probably doesn't make any sense but the gist of the matter is there is javascript breakage on the grant edit form due to a js function that no longer exists in civi.

I'm not 100% certain what that js used to achieve. Something about preselecting checkboxes? PR to follow and I'll leave up to you if you want to merge.

**Comment by JoeMurray** [comment]
Thanks.

**Comment by JoeMurray** [comment]
@monishdeb please review and close when done.

**Comment by JoeMurray** [comment]
Closing on assumption this is caught by our current testing.
