### ISSUE TITLE
Add grant program to advanced search

### ISSUE THREAD

**Issue by sdragnev** [JMAConsulting/biz.jmaconsulting.grantprograms#254]
It occurs to me there's no way to search for people who have a grant.
Within CiviGrant, one can search for grants, but not people.

Advanced search has a Grants section but grant program is not available as a filter.

**Comment by JoeMurray** [comment]
Greed this would be a good enhancement. Want tips on how to implement?

**Comment by JoeMurray** [comment]
Agreed this would be a good enhancement. Want tips on how to implement?

**Comment by JoeMurray** [comment]
Moved to https://lab.civicrm.org/extensions/grantprograms/issues/1
