### ISSUE TITLE
Add civicrm_entity_payment index

### ISSUE THREAD

**Issue by sdragnev** [JMAConsulting/biz.jmaconsulting.grantprograms#256]
Creating an index on entity_id in civicrm_entity_payment improves our grant searches about 15-20 times (in some instances).

**Comment by JoeMurray** [comment]
Yes, of course. Thanks for catching that. Could you do a Pull Request for that change?

**Comment by JoeMurray** [comment]
@monishdeb could you add this index on both initial install and on upgrade? Thx.

**Comment by JoeMurray** [comment]
Closing as transferred to https://lab.civicrm.org/extensions/grantprograms/issues/2
