### ISSUE TITLE
Find grant payments result bulk actions default to all records

### ISSUE THREAD

**Issue by sdragnev** [JMAConsulting/biz.jmaconsulting.grantprograms#257]
Unlike rest of civicrm, selecting only particular records in the grant payments result and running a bulk action using the actions dropdown affects _all_ records in the result set instead of the ones selected.

Neither the "All X records" nor the "Selected records only" radio button is selected by default so the form defaults to All records.

![civigrant_bulk_action](https://cloud.githubusercontent.com/assets/404918/12176217/5700442a-b534-11e5-9247-009ebd3c7c98.png)

Pressing "Go" will affect all 11 grant payments listed.

**Comment by JoeMurray** [comment]
@monishdeb please fix for new version.

**Comment by JoeMurray** [comment]
Closing as transferred to https://lab.civicrm.org/extensions/grantprograms/issues/3

**Comment by monishdeb** [comment]
@sdragnev this issue is fixed in the new version. Please check my comment [here](https://lab.civicrm.org/extensions/grantprograms/issues/3#note_11725)

Thanks!
