### ISSUE TITLE
Class CRM_Batch_BAO_Batch is missing checkBatchPermission

### ISSUE THREAD

**Issue by lolcodeca** [JMAConsulting/biz.jmaconsulting.grantprograms#263]
The CRM_Batch_BAO_Batch in the extension is missing a function that was introduced to the core class in 4.7.25. It means that the CiviCRM Batch export screen throws an error:

> Fatal error: Call to undefined method CRM_Batch_BAO_Batch::checkBatchPermission() in /home/web/myrnao/web/sites/all/modules/civicrm/CRM/Financial/Form/BatchTransaction.php on line 103

See: https://issues.civicrm.org/jira/browse/CRM-20988

**Comment by JoeMurray** [comment]
The override has been eliminated in newest version. Please review
